schema = 3

[mod]
  [mod.'github.com/aws/aws-sdk-go-v2']
    version = 'v1.41.9'
    hash = 'sha256-h0Nq8p8MWLNSt0rztvs6+YUAWZhkfK/t639sNb3s/PY='

  [mod.'github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream']
    version = 'v1.7.11'
    hash = 'sha256-yXQiwbJMVV0pCvX3FtSDe1oiHa4SV83mDlidh46IpFE='

  [mod.'github.com/aws/aws-sdk-go-v2/config']
    version = 'v1.32.20'
    hash = 'sha256-d7Jg7KTPOaYKuuKX+7LzdobVQdhm4tvC+bpGLkuqmV0='

  [mod.'github.com/aws/aws-sdk-go-v2/credentials']
    version = 'v1.19.19'
    hash = 'sha256-8H0WV6WNfyQA+LcVBWxVr34BphJzfrUe0Ga/FYkWgfA='

  [mod.'github.com/aws/aws-sdk-go-v2/feature/ec2/imds']
    version = 'v1.18.25'
    hash = 'sha256-SYhya/TN4FmxDJiBRydiRQH2mli5wheBbYoiwVAQwDc='

  [mod.'github.com/aws/aws-sdk-go-v2/internal/configsources']
    version = 'v1.4.25'
    hash = 'sha256-PAuufBZJfvkjKC7cEv2epPmI3qUnIIDG+4S+208OGQw='

  [mod.'github.com/aws/aws-sdk-go-v2/internal/endpoints/v2']
    version = 'v2.7.25'
    hash = 'sha256-JGDJT0PIiCYKLmGm8jWd9voYdYbxodA2JN1BkME/Sz4='

  [mod.'github.com/aws/aws-sdk-go-v2/internal/v4a']
    version = 'v1.4.26'
    hash = 'sha256-YCEJQUvjsqtEZmFZFlUfb97nuP19kKpMKSyqfAnQJAU='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding']
    version = 'v1.13.10'
    hash = 'sha256-qiYf07iN3w9qzSbiSMQ7UPbivaSYH1stWLYZjtEJyg4='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/checksum']
    version = 'v1.9.18'
    hash = 'sha256-gtMNrQyK7Cc1WrU++C4+HzWqe3YdYXDPd/7W5ZUiNHg='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/presigned-url']
    version = 'v1.13.25'
    hash = 'sha256-a86mBlnolubKgLpCk5dwiAIKJyK7C/WjuyJ74VpyyKU='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/s3shared']
    version = 'v1.19.25'
    hash = 'sha256-6K0ce4pXDKIzk4lSVbFF6zjI6CxtSCtNW8rK+LTZKco='

  [mod.'github.com/aws/aws-sdk-go-v2/service/s3']
    version = 'v1.102.2'
    hash = 'sha256-3HIERFyxOyeH3AB5x89886O87PiCzZeiIy1eSy61g+c='

  [mod.'github.com/aws/aws-sdk-go-v2/service/signin']
    version = 'v1.1.1'
    hash = 'sha256-74V10/J5eo22OJJ0NDF3EFzrhH4Joqaq3l3eg8RXQno='

  [mod.'github.com/aws/aws-sdk-go-v2/service/sso']
    version = 'v1.30.19'
    hash = 'sha256-EDPT7LLelLX4T/5/bNg+e7NK7VCfEBBsyzqxTuwhtO4='

  [mod.'github.com/aws/aws-sdk-go-v2/service/ssooidc']
    version = 'v1.36.2'
    hash = 'sha256-/nF0kvftur2ZTSBh70t/h71PATGbM1H0cVpCeKBpMFQ='

  [mod.'github.com/aws/aws-sdk-go-v2/service/sts']
    version = 'v1.42.3'
    hash = 'sha256-D0Uoj2qIn/kXeM/fJMpyUTXZ3DFt7CgJiM/3k/IlrNw='

  [mod.'github.com/aws/smithy-go']
    version = 'v1.26.0'
    hash = 'sha256-5bWwcSpU44xhvSKl8mFZML0LuDdqajwQIxnPfnCdABo='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.10.1'
    hash = 'sha256-6LBLgsh4nKkMpgRKVsYFEaGDSU1fncBcWVSjKBdfgjU='

  [mod.'github.com/go-chi/chi/v5']
    version = 'v5.3.0'
    hash = 'sha256-ufvApHNHP7n7Hhcu1ocTl0D+KiMFd7y98Kx1IZ4aHXc='

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.5.0'
    hash = 'sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U='

  [mod.'github.com/golang-jwt/jwt/v5']
    version = 'v5.3.1'
    hash = 'sha256-h7AszH+3YWL3IV0+miY9vbtU0gM/2RpuASSGAYAgWcA='

  [mod.'github.com/golang-migrate/migrate/v4']
    version = 'v4.19.1'
    hash = 'sha256-J3htVA6mxGWNik3WPWuulnnhcP0vz2n+oQOgAAO0R3U='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/jackc/pgpassfile']
    version = 'v1.0.0'
    hash = 'sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM='

  [mod.'github.com/jackc/pgservicefile']
    version = 'v0.0.0-20240606120523-5a60cdf6a761'
    hash = 'sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0='

  [mod.'github.com/jackc/pgx/v5']
    version = 'v5.9.2'
    hash = 'sha256-+R23f/i6n/iUkwc33WadubkUNIslDQraeLWdFdOXGD8='

  [mod.'github.com/jackc/puddle/v2']
    version = 'v2.2.2'
    hash = 'sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk='

  [mod.'github.com/lib/pq']
    version = 'v1.12.3'
    hash = 'sha256-tJO991B11vUvoWnGvyF8j0Dp89V/3WYCcYRcY5XuwKc='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.22'
    hash = 'sha256-6O/0jc33pKUzlzUGpH8Ekk54XgJvx6Qe7kJtbcNJAV4='

  [mod.'github.com/mattn/go-sqlite3']
    version = 'v1.14.44'
    hash = 'sha256-ZpTpBBk//7UP31nBZLIzIDbM57E4JKLWNTb/fCYeLP0='

  [mod.'github.com/muktihari/fit']
    version = 'v0.28.1'
    hash = 'sha256-13FD02gzSHk9BqU9gLTSunFLfPwEaZ0PtHC6PA0zZMs='

  [mod.'github.com/ncruces/go-strftime']
    version = 'v1.0.0'
    hash = 'sha256-GYIwYDONuv/yTE0AEugCHQbtV3oiBaco93xUNYFcVBQ='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.3.1'
    hash = 'sha256-5H8+UOtPOs+Yc+8oVT/3bugCCdbq3jFMH6eOW8dadyg='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/remyoudompheng/bigfft']
    version = 'v0.0.0-20230129092748-24d4a6f8daec'
    hash = 'sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM='

  [mod.'github.com/rogpeppe/go-internal']
    version = 'v1.10.0'
    hash = 'sha256-vR7+d0aoKTuKeTYSgZxsGhH9e5Zvxix3Zrq9SPm5+NQ='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.12.0'
    hash = 'sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws='

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

  [mod.'github.com/spf13/cast']
    version = 'v1.10.0'
    hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/spf13/viper']
    version = 'v1.21.0'
    hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='

  [mod.'github.com/stretchr/objx']
    version = 'v0.5.3'
    hash = 'sha256-4s8d7MdRKq4r7QjkIFCdwjKehc6Hi5mS4xuZ2v2QYR8='

  [mod.'github.com/stretchr/testify']
    version = 'v1.11.1'
    hash = 'sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.4'
    hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='

  [mod.'golang.org/x/crypto']
    version = 'v0.52.0'
    hash = 'sha256-/6Ajm6bIPt5xXNL5mmeNfJh4EZjgFgVlHEwp1TiC5cM='

  [mod.'golang.org/x/sync']
    version = 'v0.20.0'
    hash = 'sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y='

  [mod.'golang.org/x/sys']
    version = 'v0.45.0'
    hash = 'sha256-hkBoNazrDA67ER6sWhb+EKxx9nJ24+nz3zGy+zT5Hvw='

  [mod.'golang.org/x/text']
    version = 'v0.37.0'
    hash = 'sha256-8XDOnlPIybcDRy89fkjG5VqtIt5Ku+LmaqYhgKl7i1E='

  [mod.'golang.org/x/tools']
    version = 'v0.45.0'
    hash = 'sha256-fKsYC186cbOCJROZGUqU6UMSxvK2DZ44hlCEytLvp5c='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='

  [mod.'modernc.org/libc']
    version = 'v1.72.5'
    hash = 'sha256-cydq6kiFj4DGytqJkzqL817lJifI2lGCLrG0J9IXchw='

  [mod.'modernc.org/mathutil']
    version = 'v1.7.1'
    hash = 'sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc='

  [mod.'modernc.org/memory']
    version = 'v1.11.0'
    hash = 'sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM='

  [mod.'modernc.org/sqlite']
    version = 'v1.51.0'
    hash = 'sha256-rnxjwdV89PgD8cfobWqHzco4JlqFk+mHG5kv/MUAsF4='
