// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityFile = `-- name: CreateActivityFile :one
INSERT INTO
  activity_file (timestamp, file_repo_hash, user_id)
VALUES
  ($1, $2, $3)
RETURNING
  id, timestamp, file_repo_hash, created_at, updated_at, user_id
`

type CreateActivityFileParams struct {
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	FileRepoHash *string            `json:"file_repo_hash"`
	UserID       *int32             `json:"user_id"`
}

func (q *Queries) CreateActivityFile(ctx context.Context, arg *CreateActivityFileParams) (*ActivityFile, error) {
	row := q.db.QueryRow(ctx, createActivityFile, arg.Timestamp, arg.FileRepoHash, arg.UserID)
	var i ActivityFile
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.FileRepoHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const deleteActivityFile = `-- name: DeleteActivityFile :exec
DELETE FROM activity_file
WHERE
  id = $1
  AND user_id = $2
`

type DeleteActivityFileParams struct {
	ID     int32  `json:"id"`
	UserID *int32 `json:"user_id"`
}

func (q *Queries) DeleteActivityFile(ctx context.Context, arg *DeleteActivityFileParams) error {
	_, err := q.db.Exec(ctx, deleteActivityFile, arg.ID, arg.UserID)
	return err
}

const getActivityFile = `-- name: GetActivityFile :one
SELECT
  id, timestamp, file_repo_hash, created_at, updated_at, user_id
FROM
  activity_file
WHERE
  id = $1
  AND user_id = $2
LIMIT
  1
`

type GetActivityFileParams struct {
	ID     int32  `json:"id"`
	UserID *int32 `json:"user_id"`
}

func (q *Queries) GetActivityFile(ctx context.Context, arg *GetActivityFileParams) (*ActivityFile, error) {
	row := q.db.QueryRow(ctx, getActivityFile, arg.ID, arg.UserID)
	var i ActivityFile
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.FileRepoHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const listActivityFilesByUser = `-- name: ListActivityFilesByUser :many
SELECT
  id, timestamp, file_repo_hash, created_at, updated_at, user_id
FROM
  activity_file
WHERE
  user_id = $1
ORDER BY
  timestamp DESC
`

func (q *Queries) ListActivityFilesByUser(ctx context.Context, userID *int32) ([]*ActivityFile, error) {
	rows, err := q.db.Query(ctx, listActivityFilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ActivityFile{}
	for rows.Next() {
		var i ActivityFile
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.FileRepoHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityFile = `-- name: UpdateActivityFile :one
UPDATE activity_file
SET
  timestamp = $3,
  file_repo_hash = $4,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = $1
  AND user_id = $2
RETURNING
  id, timestamp, file_repo_hash, created_at, updated_at, user_id
`

type UpdateActivityFileParams struct {
	ID           int32              `json:"id"`
	UserID       *int32             `json:"user_id"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	FileRepoHash *string            `json:"file_repo_hash"`
}

func (q *Queries) UpdateActivityFile(ctx context.Context, arg *UpdateActivityFileParams) (*ActivityFile, error) {
	row := q.db.QueryRow(ctx, updateActivityFile,
		arg.ID,
		arg.UserID,
		arg.Timestamp,
		arg.FileRepoHash,
	)
	var i ActivityFile
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.FileRepoHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}
