// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hats.sql

package db

import (
	"context"
)

const createHat = `-- name: CreateHat :one
INSERT INTO
  hats (name, description, user_id)
VALUES
  ($1, $2, $3)
RETURNING
  id, name, description, created_at, updated_at, user_id
`

type CreateHatParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	UserID      *int32  `json:"user_id"`
}

func (q *Queries) CreateHat(ctx context.Context, arg *CreateHatParams) (*Hat, error) {
	row := q.db.QueryRow(ctx, createHat, arg.Name, arg.Description, arg.UserID)
	var i Hat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const getHat = `-- name: GetHat :one
SELECT
  id, name, description, created_at, updated_at, user_id
FROM
  hats
WHERE
  id = $1
  AND user_id = $2
LIMIT
  1
`

type GetHatParams struct {
	ID     int32  `json:"id"`
	UserID *int32 `json:"user_id"`
}

func (q *Queries) GetHat(ctx context.Context, arg *GetHatParams) (*Hat, error) {
	row := q.db.QueryRow(ctx, getHat, arg.ID, arg.UserID)
	var i Hat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const listHatsByUser = `-- name: ListHatsByUser :many
SELECT
  id, name, description, created_at, updated_at, user_id
FROM
  hats
WHERE
  user_id = $1
`

func (q *Queries) ListHatsByUser(ctx context.Context, userID *int32) ([]*Hat, error) {
	rows, err := q.db.Query(ctx, listHatsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Hat{}
	for rows.Next() {
		var i Hat
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
