// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityFile struct {
	ID           int32              `json:"id"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	FileRepoHash *string            `json:"file_repo_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UserID       *int32             `json:"user_id"`
}

type Hat struct {
	ID          int32              `json:"id"`
	Name        *string            `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserID      *int32             `json:"user_id"`
}

type User struct {
	ID          int32              `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Password    []byte             `json:"password"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
