// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	//
	// -- name: ListUsers :many
	// SELECT
	//   id,
	//   email,
	//   name,
	//   created_at,
	//   updated_at
	// FROM
	//   users
	// ORDER BY
	//   name;
	//
	CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error)
	GetUser(ctx context.Context, id int32) (*GetUserRow, error)
	// --
	// really we don't want to select password except specifically for auth.
	// This query is useful for auth only and for nothing else, which should discourage misuse
	SelectEmailPasswordForAuth(ctx context.Context, email string) (*SelectEmailPasswordForAuthRow, error)
}

var _ Querier = (*Queries)(nil)
