// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (email, display_name, password)
VALUES
  ($1, $2, $3)
RETURNING
  id,
  email,
  display_name,
  created_at,
  updated_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	Password    []byte `json:"password"`
}

type CreateUserRow struct {
	ID          int32              `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// -- name: ListUsers :many
// SELECT
//
//	id,
//	email,
//	name,
//	created_at,
//	updated_at
//
// FROM
//
//	users
//
// ORDER BY
//
//	name;
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT
  id,
  email,
  display_name,
  created_at,
  updated_at
FROM
  users
WHERE
  id = $1
LIMIT
  1
`

type GetUserRow struct {
	ID          int32              `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (*GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const selectEmailPasswordForAuth = `-- name: SelectEmailPasswordForAuth :one
SELECT
  id,
  email,
  display_name,
  password
FROM
  users
WHERE
  email = $1
LIMIT
  1
`

type SelectEmailPasswordForAuthRow struct {
	ID          int32  `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	Password    []byte `json:"password"`
}

// --
// really we don't want to select password except specifically for auth.
// This query is useful for auth only and for nothing else, which should discourage misuse
func (q *Queries) SelectEmailPasswordForAuth(ctx context.Context, email string) (*SelectEmailPasswordForAuthRow, error) {
	row := q.db.QueryRow(ctx, selectEmailPasswordForAuth, email)
	var i SelectEmailPasswordForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Password,
	)
	return &i, err
}
