// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO
  workouts (
    distance_miles,
    time_seconds,
    speed_mph,
    pace_min_per_mile,
    start_time,
    end_time,
    activity_file_id,
    user_id
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
  id, distance_miles, time_seconds, speed_mph, pace_min_per_mile, start_time, end_time, activity_file_id, created_at, updated_at, user_id
`

type CreateWorkoutParams struct {
	DistanceMiles  *float64           `json:"distance_miles"`
	TimeSeconds    *float64           `json:"time_seconds"`
	SpeedMph       *float64           `json:"speed_mph"`
	PaceMinPerMile *float64           `json:"pace_min_per_mile"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	ActivityFileID *int32             `json:"activity_file_id"`
	UserID         int32              `json:"user_id"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg *CreateWorkoutParams) (*Workout, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.DistanceMiles,
		arg.TimeSeconds,
		arg.SpeedMph,
		arg.PaceMinPerMile,
		arg.StartTime,
		arg.EndTime,
		arg.ActivityFileID,
		arg.UserID,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.DistanceMiles,
		&i.TimeSeconds,
		&i.SpeedMph,
		&i.PaceMinPerMile,
		&i.StartTime,
		&i.EndTime,
		&i.ActivityFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts
WHERE
  id = $1
  AND user_id = $2
`

type DeleteWorkoutParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg *DeleteWorkoutParams) error {
	_, err := q.db.Exec(ctx, deleteWorkout, arg.ID, arg.UserID)
	return err
}

const getWorkout = `-- name: GetWorkout :one
SELECT
  id, distance_miles, time_seconds, speed_mph, pace_min_per_mile, start_time, end_time, activity_file_id, created_at, updated_at, user_id
FROM
  workouts
WHERE
  id = $1
  AND user_id = $2
LIMIT
  1
`

type GetWorkoutParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetWorkout(ctx context.Context, arg *GetWorkoutParams) (*Workout, error) {
	row := q.db.QueryRow(ctx, getWorkout, arg.ID, arg.UserID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.DistanceMiles,
		&i.TimeSeconds,
		&i.SpeedMph,
		&i.PaceMinPerMile,
		&i.StartTime,
		&i.EndTime,
		&i.ActivityFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}

const getWorkoutsByActivityFile = `-- name: GetWorkoutsByActivityFile :many
SELECT
  id, distance_miles, time_seconds, speed_mph, pace_min_per_mile, start_time, end_time, activity_file_id, created_at, updated_at, user_id
FROM
  workouts
WHERE
  activity_file_id = $1
  AND user_id = $2
ORDER BY
  start_time DESC
`

type GetWorkoutsByActivityFileParams struct {
	ActivityFileID *int32 `json:"activity_file_id"`
	UserID         int32  `json:"user_id"`
}

func (q *Queries) GetWorkoutsByActivityFile(ctx context.Context, arg *GetWorkoutsByActivityFileParams) ([]*Workout, error) {
	rows, err := q.db.Query(ctx, getWorkoutsByActivityFile, arg.ActivityFileID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.DistanceMiles,
			&i.TimeSeconds,
			&i.SpeedMph,
			&i.PaceMinPerMile,
			&i.StartTime,
			&i.EndTime,
			&i.ActivityFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsByUser = `-- name: ListWorkoutsByUser :many
SELECT
  id, distance_miles, time_seconds, speed_mph, pace_min_per_mile, start_time, end_time, activity_file_id, created_at, updated_at, user_id
FROM
  workouts
WHERE
  user_id = $1
ORDER BY
  start_time DESC
`

func (q *Queries) ListWorkoutsByUser(ctx context.Context, userID int32) ([]*Workout, error) {
	rows, err := q.db.Query(ctx, listWorkoutsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.DistanceMiles,
			&i.TimeSeconds,
			&i.SpeedMph,
			&i.PaceMinPerMile,
			&i.StartTime,
			&i.EndTime,
			&i.ActivityFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkout = `-- name: UpdateWorkout :one
UPDATE workouts
SET
  distance_miles = $3,
  time_seconds = $4,
  speed_mph = $5,
  pace_min_per_mile = $6,
  start_time = $7,
  end_time = $8,
  activity_file_id = $9,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = $1
  AND user_id = $2
RETURNING
  id, distance_miles, time_seconds, speed_mph, pace_min_per_mile, start_time, end_time, activity_file_id, created_at, updated_at, user_id
`

type UpdateWorkoutParams struct {
	ID             int32              `json:"id"`
	UserID         int32              `json:"user_id"`
	DistanceMiles  *float64           `json:"distance_miles"`
	TimeSeconds    *float64           `json:"time_seconds"`
	SpeedMph       *float64           `json:"speed_mph"`
	PaceMinPerMile *float64           `json:"pace_min_per_mile"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	ActivityFileID *int32             `json:"activity_file_id"`
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg *UpdateWorkoutParams) (*Workout, error) {
	row := q.db.QueryRow(ctx, updateWorkout,
		arg.ID,
		arg.UserID,
		arg.DistanceMiles,
		arg.TimeSeconds,
		arg.SpeedMph,
		arg.PaceMinPerMile,
		arg.StartTime,
		arg.EndTime,
		arg.ActivityFileID,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.DistanceMiles,
		&i.TimeSeconds,
		&i.SpeedMph,
		&i.PaceMinPerMile,
		&i.StartTime,
		&i.EndTime,
		&i.ActivityFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return &i, err
}
